CREATE TABLE SALARYBANDS 
(
  SALARYBAND VARCHAR2(20) NOT NULL 
, MINIMUM NUMBER 
, MAXIMUM NUMBER 
, ENDOFYEARBONUS DECIMAL 
, CONSTRAINT SALARYBANDS_PK PRIMARY KEY 
  (
    SALARYBAND 
  )
  ENABLE 
);
